spring:
  application:
    name: RKVerse

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  main:
    allow-circular-references: true

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 10
        max-page-size: 100

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 300MB
      file-size-threshold: 2MB

server:
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: 300MB
    max-part-count: 300

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: ${ACCESS_TOKEN_EXP}
  refresh-token: ${REFRESH_TOKEN_EXP}

cloudflare:
  r2:
    endpoint: ${ENDPOINT_R2:}
    access-key: ${ACCESS_KEY:}
    secret-key: ${SECRET_KEY:}
    bucket-name: ${BUCKET_NAME:rkverse-dev}
    public-domain: ${R2_CUSTOM_DOMAIN:}